### ISSUE TITLE
notifier uses tls_certcheck 0 for msmtp option

### ISSUE THREAD

**Issue by lbeltrame** [CZ-NIC/turris-misc#4]
As the subject says. This is generally a bad idea, because like this we can't know if the certificate we see is genuine, or made by someone else who's MITMing us.

**Comment by VojtechMyslivec** [comment]
Fixed by https://gitlab.labs.nic.cz/turris/user-notify/merge_requests/4 and released in TOS 4.0 and 3.11.5
